[build]
  command = "bun run build"
  publish = "_site"

[build.environment]
  BUN_VERSION = "1.3.2"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/host-meta"
  to = "https://fed.brid.gy/.well-known/host-meta"
  status = 200
  force = true
